Repository ifthen-gg/ifthen.gg, pull requests merged in 2021-05, with the labels that each got.

#18 ✨Create AppBar Component
  src/components/AppBar/AppBar.module.css
  src/components/AppBar/AppBar.stories.tsx
  src/components/AppBar/AppBar.tsx
  src/components/icons/CloseIcon.tsx
  src/components/icons/MinimizeIcon.tsx
  src/components/icons/RainbowKraken.tsx
  src/index.css
Labels: component

#23 🔨 Support local-server debugging
  overwolf/manifest.json
Labels: development

#25 📝 Add issue templates
  .github/ISSUE_TEMPLATE/event-template.md
  .github/ISSUE_TEMPLATE/trigger-template.md
Labels: documentation

#24 ✨ Add first trigger, action and apps
  .eslintrc.js
  jest.config.js
  overwolf/manifest.json
  package-lock.json
  package.json
  setup/overwolf.js
  src/actions/index.ts
  src/actions/openWebsite.test.ts
  src/actions/openWebsite.ts
  src/actions/types.ts
  src/apps/index.ts
  src/apps/leagueOfLegends.ts
  src/apps/types.ts
  src/apps/valorant.ts
  src/assets/apps/leagueOfLegends.png
  src/assets/apps/valorant.png
  src/background.tsx
  src/components/SelectTrigger/SelectTrigger.module.css
  src/components/SelectTrigger/SelectTrigger.stories.tsx
  src/components/SelectTrigger/SelectTrigger.tsx
  src/components/icons/AppSelectIcon.tsx
  src/components/icons/SearchIcon.tsx
  src/index.css
  src/triggers/index.ts
  src/triggers/leagueQueue.test.ts
  src/triggers/leagueQueue.ts
  src/triggers/triggerTarget.test.ts
  src/triggers/triggerTarget.ts
  src/triggers/types.ts
  typings.d.ts
Labels: enhancement
